server:
  port: 8763
spring:
  application:
    name: spbootFeign
    
#开启熔断功能    
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      