server:
  port: 8762

spring:
  profiles:
    active: peer2
  
eureka:
  instance:
    hostname: peer2
  server:
    enableSelfPreservation: false
    leaseRenewalIntervalInSeconds: 2
  client:
    #禁止注册自身
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
      