server:
  port: 8775
spring:
  application:
    name: spbootZuul
    
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spbootFeign
    api-b:
      path: /api-b/**
      serviceId: spbootRibbon
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

      